# errorMatch: "ERROR at "
cmd: "/Users/evgenii/miniconda3/bin/python -u '{FILE_ACTIVE}'"
name: "Run Python"
errorMatch:
    - \s+File \"(?<file>.*)\", line (?<line>\d+).*?\n(?:[\s|\S]+)\n(?<message>.*rror:.*)

targets:
    pytest:
        cmd: "pytest -s '{FILE_ACTIVE}'"

    LaTeX:
        cmd: "cd '{FILE_ACTIVE_PATH}' && cd .. && /Library/TeX/texbin/pdflatex assignment.tex && open -a Skim.app assignment.pdf"

    LeTeXRemoveAux:
        cmd: "rm -f '{FILE_ACTIVE_PATH}/{FILE_ACTIVE_NAME_BASE}.aux'"
